version: '3'
services:
  nodeserver:
    build:
      context: ./got
    depends_on:
      - mongo
    ports:
      - "5005:5000"
  mongo:
    image: mongo
    ports:
      - 27017:27017
  nginx:
    #image: nginx
    restart: always 
    build:
      context: ./nginx
    ports:
      - "80:80" 